# Basic Tensor operations and GradientTape.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def tf_constant(array):
    tf_constant_array = tf.constant(array)
    return tf_constant_array

In [3]:
tmp_array = np.arange(1,10)
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [4]:
def tf_square(array):
    array = tf.constant(array)
    tf_squared_array = tf.square(array)
    return tf_squared_array

In [5]:
tmp_array = tf.constant(np.arange(1, 10))
x = tf_square(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

#### Reshapes a tensor.

In [6]:
def tf_reshape(array, shape):
    array = tf.constant(array)
    tf_reshaped_array = tf.reshape(array, shape)
    return tf_reshaped_array

In [7]:
tmp_array = np.array([1,2,3,4,5,6,7,8,9])
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

#### Casts a tensor to a new type.

In [8]:
def tf_cast(array, dtype):
    array = tf.constant(array)
    tf_cast_array = tf.cast(array, dtype=dtype)
    return tf_cast_array

In [9]:
tmp_array = [1,2,3,4]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

#### Returns an element-wise x * y.

In [10]:
def tf_multiply(tensor1, tensor2):
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    product = tf.multiply(tensor1, tensor2)
    return product

In [11]:
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

#### Returns x + y element-wise.

In [12]:
def tf_add(tensor1, tensor2):
    tensor1 = tf.constant(tensor1)
    tensor2 = tf.constant(tensor2)
    total = tf.add(tensor1, tensor2)
    return total

In [13]:
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([5, 7, 9])>

#### Gradient Tape.

In [14]:
def tf_gradient_tape(x):
    with tf.GradientTape() as t:
        t.watch(x)   
        y = 3 * x ** 3 - 2 * x ** 2 + x
        z = tf.reduce_sum(y)
    dz_dx = t.gradient(z, x)
    return dz_dx

In [15]:
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

29.0

## References
##### Coursera: Custom and Distributed Training with TensorFlow [course](https://www.coursera.org/learn/custom-distributed-training-with-tensorflow).